name: Print Hello World
on:
    push:
jobs:
    printHelloWorld:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello World"
  
    addTwoNumbers:
      runs-on: ubuntu-latest
      steps:
            - name: Repo clone
              uses: git checkout@v4

            - name: Print Hello World
              run: ndoe random.js
